version: '3'
services:
  metabase:
    image: metabase/metabase:v0.29.3
    container_name: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: db1
      MB_DB_PORT: 15432
      MB_DB_USER: user1
      MB_DB_PASS: pass1
      MB_DB_HOST: docker.for.mac.localhost
      JAVA_TIMEZONE: Asia/Mumbai
      JAVA_TOOL_OPTIONS: -Xmx512m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
        labels: "metabase"
    restart: always

  nginx:
    image: nginx:1.15.0
    container_name: nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
        labels: "nginx"
